#ifndef CG_DEFINES
#define CG_DEFINES

#define STATE_SIZE 2
#define CONTROL_SIZE 1
#define KNOT_POINTS 5


#define GATO_BLOCK_ID (blockIdx.x)
#define GATO_THREAD_ID (threadIdx.x)
#define GATO_THREADS_PER_BLOCK THREADS_PER_BLOCK
#define GATO_NUM_BLOCKS   NUMBER_OF_BLOCKS
#define GATO_LEAD_THREAD (GATO_THREAD_ID == 0)
#define GATO_LEAD_BLOCK (GATO_BLOCK_ID == 0)
#define GATO_LAST_BLOCK (GATO_BLOCK_ID == GATO_NUM_BLOCKS - 1)


#define PRINT_THREAD    0
#define GATO_PRINT_BLOCK_THREAD (1 && (GATO_BLOCK_ID == 0) && GATO_LEAD_THREAD)
#define GATO_PRINT_BLOCK_THREAD2 (1 && (GATO_BLOCK_ID == 2) && threadIdx.x == 0)


#define STATES_SQ       STATE_SIZE*STATE_SIZE
#define CONTROLS_SQ     CONTROL_SIZE*CONTROL_SIZE
#define STATES_S_CONTROLS STATE_SIZE+CONTROL_SIZE
#define STATES_P_CONTROLS STATE_SIZE*CONTROL_SIZE

#define PI          static_cast<T>(3.14159)
#define GRAVITY     static_cast<T>(9.81)



#endif